BUG: Remove invalid Qt connection from RigitAlignmentModule
This commit fixes the following error reported when clicking on the
collapsible button (it was most likely introduced due to a copy/paste
mistake in commit 6fb88b7):

Traceback (most recent call last):
  File "/path/to/Slicer-build/lib/SlicerSALT-4.11/qt-scripted-modules/RigidAlignmentModule.py", line 76, in <lambda>
    lambda: self.onSelectedCollapsibleButtonOpen(
AttributeError: RigidAlignmentModuleWidget instance has no attribute 'onSelectedCollapsibleButtonOpen'